### ISSUE TITLE
Research Headless CMS systems

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-Foundation-Next-Website#123]
Research Headless CMS systems, for us to use with our Reactjs website, and our  React Native mobile app.

Definition of done

- [x] Checkout out several popular CMS systems here https://jamstack.org/headless-cms/
- [x] Tried run them as well and see how easy it is the setup, and how easy and flexible and featured the dashboard is
- [x] Compare and document the best options in your opinion.

Some criteria that is important, please also try to document other criteria that you think might be important:

- dashboard
- compatible to use with Reactjs and React Native apps
- open sourced
- pricing model
- what kind of content is supported
- is it gitbased, can we get it to sync with Github
- identity system (how do people log into the admin dashboard and update content)

**Comment by Mrak1985** [comment]
https://docs.google.com/spreadsheets/d/1iZU4HmtNj7a9rYJtnBSvveKTE_qd9ZVpYX0rQWkv5DM/edit?usp=sharing
