### ISSUE TITLE
Website TonomyID section 1; Landing page

### ISSUE THREAD

**Issue by TheFakeBasS** [Tonomy-Foundation/Tonomy-Foundation-Next-Website#126]
Create the "landing" component for the TonomyID page.
See the Page plans here;
https://docs.google.com/document/d/1S-lMLZGHhtt3maQXEE51CJpejGkIyyyFOTUQ1zcBD_A/

**definition of done**
- [x] View the section in the page plans
- [x] Go through the template and choose one fitting to the section
- [x] Implement the section as the page plan dictates
- [x] Add the page plan content to the component
- [x] Submit your product for feedback
- [ ] Reviewed & feedback implemented to satisfaction of PO

**Comment by Xdsylar** [comment]
![image.png](https://images.zenhubusercontent.com/63232ebaf7858659f273f64d/7a1437f2-5463-4252-a54c-73563b0f95dd) 

I personally don't know who did this section, but it perfectly fits the description of my task so I think someone else did this one for me
