### ISSUE TITLE
Website TonomyID section 3; Features!

### ISSUE THREAD

**Issue by TheFakeBasS** [Tonomy-Foundation/Tonomy-Foundation-Next-Website#128]
Create the "Features" component for the TonomyID page.
See the Page plans here;
https://docs.google.com/document/d/1S-lMLZGHhtt3maQXEE51CJpejGkIyyyFOTUQ1zcBD_A/

**definition of done**
- [x] View the section in the page plans
- [x] Go through the template and choose one fitting to the section
- [x] Implement the section as the page plan dictates
- [x] Add the page plan content to the component
- [x] Submit your product for feedback
- [ ] Reviewed & feedback implemented to satisfaction of PO

**Comment by Xdsylar** [comment]
![image.png](https://images.zenhubusercontent.com/63232ebaf7858659f273f64d/f5e75192-82c5-4a58-9c3e-ed5074ebed65) currently it looks like this

**Comment by Xdsylar** [comment]
![image.png](https://images.zenhubusercontent.com/63232ebaf7858659f273f64d/ae3a4f7f-0d05-4e73-b5c2-06f6f1e19a42) this is how I want to make it look

**Comment by Xdsylar** [comment]
update!!

It is now gonna look more like this because of Jacks feedback![image.png](https://images.zenhubusercontent.com/63232ebaf7858659f273f64d/19fd4d7e-b39f-4cd1-9ccb-2aed0c6cbf0f)

**Comment by Xdsylar** [comment]
![image.png](https://images.zenhubusercontent.com/63232ebaf7858659f273f64d/60afa8e5-7b07-4e26-9101-9931feeb9b6d)

this is how it turned out. I've made it all the same height

**Comment by Xdsylar** [comment]
and I updated the little icons at the top of each feature to imo more fitting ones
