### ISSUE TITLE
Website TonomyID section 4; Why is it better?

### ISSUE THREAD

**Issue by TheFakeBasS** [Tonomy-Foundation/Tonomy-Foundation-Next-Website#129]
Create the "Why is TID better?" component for the TonomyID page.
See the Page plans here;
https://docs.google.com/document/d/1S-lMLZGHhtt3maQXEE51CJpejGkIyyyFOTUQ1zcBD_A/

**definition of done**
- [x] View the section in the page plans
- [x] Go through the template and choose one fitting to the section
- [x] Implement the section as the page plan dictates
- [x] Add the page plan content to the component
- [x] Submit your product for feedback
- [ ] Reviewed & feedback implemented to satisfaction of PO

**Comment by NotTheRealMax** [comment]
![afbeelding.png](https://images.zenhubusercontent.com/63232df0b43026151bb6f094/04ad2fc9-3bca-4605-a66b-4391c82dc3f2)
