### ISSUE TITLE
Website mailchimp contact form fix & embed

### ISSUE THREAD

**Issue by Riae** [Tonomy-Foundation/Tonomy-Foundation-Next-Website#136]
**Description:** We need a contact form for our contact page. This is done through mailchimp.
We need to connect the form in the template to mailchimp.

current contact page: https://tonomy.foundation/contact/
Contact template page: https://tonomy-foundation-template.vercel.app/contact/
Mailchimp dashboard: https://us12.admin.mailchimp.com/lists/dashboard/signup-forms/

Ask either Jack or Aymen for the Mailchimp login details.
Only do stuff with the signup-forms, if you want to do something else let Jack know.

- What is the purpose/reason for this task?
- What current or future goal of the TF does it help achieve?

**Definition of done:**

- [x] Contact template piece is on the website
- [ ] Mailchimp works with the contact page on our website

**Comment by Mrak1985** [comment]
@Riae @yvzblgcyln put the comments, why are you blocked please?

**Comment by Riae** [comment]
data sending works, we're stuck on giving the data a place to be sent to, so the request times out

**Comment by kamitor** [comment]
Needs update?
