### ISSUE TITLE
Website TonomyID section 8; Who is using tonomy ID

### ISSUE THREAD

**Issue by TheFakeBasS** [Tonomy-Foundation/Tonomy-Foundation-Next-Website#147]
Create the "Who is using" component for the TonomyID page.
See the Page plans here;
https://docs.google.com/document/d/1S-lMLZGHhtt3maQXEE51CJpejGkIyyyFOTUQ1zcBD_A/

**definition of done**

- [ ] View the section in the page plans
- [ ]  Go through the template and choose one fitting to the section
- [ ]  Implement the section as the page plan dictates
- [ ]  Add the page plan content to the component
- [ ]  Submit your product for feedback
- [ ]  Reviewed & feedback implemented to satisfaction of PO

**Comment by kamitor** [comment]
Very cool, Now small task for each of the sections
