### ISSUE TITLE
website footer - update the footer

### ISSUE THREAD

**Issue by NotTheRealMax** [Tonomy-Foundation/Tonomy-Foundation-Next-Website#7]
Definition of done

- [x] footer has links to socials
- [x] footer has link to Linkedin jobs
- [x] copyright notice

**Comment by TheFakeBasS** [comment]
![image.png](https://images.zenhubusercontent.com/63232ea6ae5d18b3673d537f/a5a445ca-4f91-4af0-92dd-1478e947fd68)
